### ISSUE TITLE
Add Defense Shield Timer

### ISSUE THREAD

**Issue by felipeko** [Detect/swam_extensions#10]
It would be very useful to have this for defense too, but I don't thinks this one need to send messages on team chat as the players with the timer will probably be covering the shield spot.

**Comment by Detect** [comment]
@felipeko thoughts on UX for defense vs offense?

**Comment by fabiospampinato** [comment]
@Detect maybe something like this?

<img width="534" alt="shield_counters" src="https://user-images.githubusercontent.com/1812093/37976134-1058a86a-31e1-11e8-893c-7c4f4a887945.png">

----

**Edit**: I've misread UX as UI :neckbeard:

**Comment by Detect** [comment]
@fabiospampinato That's where the flag carrier name is usually displayed. I do like the consistency of the boxes and fonts tho. How about:

![](https://cl.ly/3I381n3a082o/shield%20timer%20with%20def%20v1.png)

Also, for messages that don't need to be send to team chat (ie. defense shield timer), we can use consider using local player only messages like how SWAM does it:

![](https://cl.ly/3B1D25303B1Y/Screen%20Shot%202018-03-27%20at%2011.32.19%20AM.png)

**Comment by fabiospampinato** [comment]
> How about: [image]

That looks good to me. Another option, for symmetry:

![shields](https://user-images.githubusercontent.com/1812093/37980611-cbd5f476-31eb-11e8-957d-5e6de2918106.png)

> Also, for messages that don't need to be send to team chat (ie. defense shield timer), we can use consider using local player only messages like how SWAM does it:

That would be nice.

**Comment by Detect** [comment]
i like @fabiospampinato's mockup above.

implementation detail: make sure the font size fits 4 characters (ie. 102s) or 3 characters without the s.

**Comment by Molesmalo** [comment]
For local messages, use UI.addChatMessage.

From SWAM code: 
```js
UI.addChatMessage("Mod:  Press H to check StarMash shortcuts.".bold());
```

**Comment by Detect** [comment]
Some players think defense is op and having an offense only shield timer makes O more fun and reduces defense shield sitting. A case for not having a defense timer.

**Comment by Molesmalo** [comment]
Yeah, its a very defensive game, and imho defensive timer would just worsen that...

**Comment by Detect** [comment]
Let's not do a defense timer then. At least not in this extension.
