### ISSUE TITLE
Improve shield timer activation/deactivation messages

### ISSUE THREAD

**Issue by felipeko** [Detect/swam_extensions#11]
It shouldn't send messages when there's no timer activated, as it does nothing useful. 

The activation/deactivation messages could have the current time.

Also throttling the messages for a few seconds would be nice.

**Comment by Detect** [comment]
@felipeko which messages? the "enabled/disabled sending shield timer to team chat"?

**Comment by felipeko** [comment]
Yes

**Comment by Detect** [comment]
pressing `b` to enable/disable sending to team chat will affect future messages to team chat when auto-team is on, so some sort of feedback of the toggle state might be useful to the player. can consider using local player only messages like how SWAM does on start.

![](https://cl.ly/3B1D25303B1Y/Screen%20Shot%202018-03-27%20at%2011.32.19%20AM.png)

**Comment by Detect** [comment]
if we're talking about the "started enemy shield timer" message, we could replace it with the "X seconds till enemy shield" where X is the spawn time (currently 105 - 3 second delay). that might actually be more useful if we implement #8.

**Comment by Molesmalo** [comment]
I'll leave this also here:

For local messages, use UI.addChatMessage.

From SWAM code: 
```js
UI.addChatMessage("Mod:  Press H to check StarMash shortcuts.".bold());
```

**Comment by Detect** [comment]
Added timestamps and used local player messages in v0.9.  cc @felipeko 

![](https://cl.ly/0W1j2P27152Z/Screen%20Shot%202018-03-29%20at%205.29.07%20AM.png)
