### ISSUE TITLE
Support randomly spawned shields

### ISSUE THREAD

**Issue by Detect** [Detect/swam_extensions#17]
Add info for randomly spawned shields ~~near enemy base~~ when player sees them.

Info to display:

- ~~Distance to enemy flag~~
- ~~Time to enemy flag? (calculated from ship speed or hardcoded speed?)~~
- ~~Direction to enemy flag~~
- Direction and estimated time to fly to shield

How to display:

- Local message
- ~~Team chat message? (use team chat settings)~~

How to implement:

- Use mobAdded type shield event handler
- ~~Check if within bounding box of area around enemy flag~~
- Need pathfinding algorithm for distance/time to enemy flag?

**Comment by Detect** [comment]
@Molesmalo do you have any info on the A* you used for auto-pilot?

**Comment by Molesmalo** [comment]
Sent you code snippets to get the path.
