### ISSUE TITLE
Send timer to team manually

### ISSUE THREAD

**Issue by Molesmalo** [Detect/swam_extensions#2]
When the auto-sending of messages is disabled, you might want to provide an alternative method to send messages manually. Like a key-bind or clicking the icon.

As you already use B, you could check: 
- if you are not sending messages, B sends the current timer.
- if you are sending, B stops,

**Comment by Detect** [comment]
@Molesmalo does the latest version do what you'd expect for pressing B when auto-team chat is disabled?

**Comment by Molesmalo** [comment]
Just tested it!  Yes, it does.

One more thing though. Could it be possible that when auto-team is enabled, the timer remains visible when i stop it with 'b'?  (So, if i press again, it sends manually like if the auto sending is disabled).

Only if it doesn't require too much work, as it's also perfect as it's now too!

**Comment by Detect** [comment]
@Molesmalo Updated it, so that:

> - If auto-team chat is enabled, pressing b key will toggle (pause/resume) sending timer to team chat.
> - If auto-team chat is disabled, pressing b key will send current timer to team chat.
