### ISSUE TITLE
function settingsProvider is global

### ISSUE THREAD

**Issue by Molesmalo** [Detect/swam_extensions#20]
Hi D.

Requesting a small change on line 17:

```js
	settingsProvider = () => {
```

should be

```js
	let settingsProvider = () => {
```

As there's no var, let, const keywords,  it's declared as global, thus leaking from the module.
I would also recommend adding (I forgot to add it on the examples!)
```js
"use strict";
```

Thanks!

**Comment by Detect** [comment]
@Molesmalo fixed
