### ISSUE TITLE
Add settings to customize timer intervals

### ISSUE THREAD

**Issue by Molesmalo** [Detect/swam_extensions#3]
It would be nice to be able to set the intervals when sending chat messages automatically.

I don't know what would be the best option here:

If a textbox where the user inputs a comma separated list like: "60, 30, 10" (the problem with this is that i didnt provide a validation callback yet for the SettingsProvider).

Or maybe a combo box with some predefined options like (just as example):
[90, 60, 30, 20, 10, 5]
[60, 30, 10, 5]
[60, 30, 10]
[60, 10]
It's more restrictive but also simpler.

Or even checkbox for different values [90, 60, 30, 20, 10, 5].   =P

**Comment by Detect** [comment]
@Molesmalo v0.4 allows custom intervals via comma separated textbox in mod settings. pls lmk if it works for you.

**Comment by Molesmalo** [comment]
yeah, it works! 😄
